/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eurOeSol from "./EUROe.sol";
export type { eurOeSol };
export type { PaymentContract } from "./PaymentContract";
export type { USDC } from "./USDC";
